### ISSUE TITLE
Special exchange section for project donations

### ISSUE THREAD

**Issue by jeroz1** [RavenProject/ravenproject.github.io#67]
I think there should be a special section mentioning exchanges that donate back to the project. 

- Vertbase
- Changeangel
- DynX

**Comment by ladams1776** [comment]
Newb developer question here: Are issues items that have been voted on and that can be worked on? Or do they need to be approved? Do we have a schematic of what we may want it to look like or where we might want it?

**Comment by jeroz1** [comment]
I think an extra section on the top would suffice here: https://ravencoin.org/buy-ravencoin/. Which highlights that trader fees are partly donated back to the project. In addition, I think it would be good to add a little note below the exchange logos on the front page. Much like how the symbols below the third party wallets indicate for which OS they are. 

FYI Vertbase changed to https://www.sequoir.com/

**Comment by ladams1776** [comment]
Ok, please correct me where I am off please.

1. We want a new section, under the **Ravencoin Buying Guide**, that will say "Trader fees are partly donated back to the project".

2. On the Homepage, we want to update the Exchange section, so that at the bottom of each Exchange card (below the icon, but in the card) will say: "Partial trading fees are partly donated back to Ravencoin project".

3. Vertbase link is broken and we now want to replace it with: https://www.sequoir.com/ 

Please correct me where I went astray. I also have SS of #1. They will not be exactly what we want, I am sure, but they will help guide me, based on your feedback.

**Comment by jeroz1** [comment]
Sounds about right.

To build and test locally, there's a guide here: https://docs.github.com/en/github/working-with-github-pages/testing-your-github-pages-site-locally-with-jekyll

**Comment by ladams1776** [comment]
This might be able to be closed now.
